name: Laravel

on:
  push:
    branches: [ "TC-2-Como-usuario-podr-registrarme-en-la-p-gina-web-para-poder-hacer-uso-de-varias-funcionalidades" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: read
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  statuses: write

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Install npm Dependencies
      run: npm install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Linkeamos el storage
      run: php artisan storage:link
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/technoblog.mysql
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: database/technoblog.mysql
      run: vendor/bin/phpunit

    - name: Corremos tests
      run: npm test
    
    - name: Construimos imagen docker
      run: docker build -t technoblog .